# Generated by Django 5.2.8 on 2026-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_shop_id_d0bcbf_idx',
            old_name='products_pr_shop_i_3bb1b5_idx',
        ),
    ]
