# Generated by Django 5.2.8 on 2026-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_shop_id_a0d636_idx',
            old_name='sales_sale_shop_id_7035a1_idx',
        ),
    ]
